# Generated by Django 5.1.4 on 2025-01-09 23:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Code', models.CharField(max_length=3)),
                ('Created', models.DateTimeField(default=django.utils.timezone.now)),
                ('CreatedBy', models.CharField(default='SERVER', max_length=50)),
                ('Updated', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('UpdatedBy', models.CharField(default='SERVER', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Bank',
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Code', models.CharField(max_length=3)),
                ('Created', models.DateTimeField(default=django.utils.timezone.now)),
                ('CreatedBy', models.CharField(default='SERVER', max_length=50)),
                ('Updated', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('UpdatedBy', models.CharField(default='SERVER', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Classification',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Code', models.CharField(max_length=3)),
                ('Created', models.DateTimeField(default=django.utils.timezone.now)),
                ('CreatedBy', models.CharField(default='SERVER', max_length=50)),
                ('Updated', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('UpdatedBy', models.CharField(default='SERVER', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Country',
            },
        ),
        migrations.CreateModel(
            name='Uom',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Code', models.CharField(max_length=3)),
                ('Created', models.DateTimeField(default=django.utils.timezone.now)),
                ('CreatedBy', models.CharField(default='SERVER', max_length=50)),
                ('Updated', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('UpdatedBy', models.CharField(default='SERVER', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Uom',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Code', models.CharField(max_length=3)),
                ('Created', models.DateTimeField(default=django.utils.timezone.now)),
                ('CreatedBy', models.CharField(default='SERVER', max_length=50)),
                ('Updated', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('UpdatedBy', models.CharField(default='SERVER', max_length=50, null=True)),
                ('idCountry', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.country')),
            ],
            options={
                'db_table': 'City',
            },
        ),
    ]
