# Generated by Django 3.1.7 on 2021-03-09 03:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Code', models.CharField(max_length=3)),
                ('Created', models.DateTimeField(default=django.utils.timezone.now)),
                ('CreatedBy', models.CharField(default='SERVER', max_length=50)),
                ('Updated', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('UpdatedBy', models.CharField(default='SERVER', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Country',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Code', models.CharField(max_length=3)),
                ('Created', models.DateTimeField(default=django.utils.timezone.now)),
                ('CreatedBy', models.CharField(default='SERVER', max_length=50)),
                ('Updated', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('UpdatedBy', models.CharField(default='SERVER', max_length=50, null=True)),
                ('idCountry', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.country')),
            ],
            options={
                'db_table': 'City',
            },
        ),
    ]
