# Generated by Django 5.1.4 on 2025-01-09 23:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('ZipCode', models.CharField(max_length=255)),
                ('RFC', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('Phone1', models.CharField(max_length=25, null=True)),
                ('Phone2', models.CharField(max_length=25, null=True)),
                ('Created', models.DateTimeField(default=django.utils.timezone.now)),
                ('CreatedBy', models.CharField(default='SERVER', max_length=50)),
                ('Updated', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('UpdatedBy', models.CharField(default='SERVER', max_length=50, null=True)),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.city')),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.country')),
            ],
            options={
                'db_table': 'Client',
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=25)),
                ('Email', models.CharField(default='', max_length=255)),
                ('Created', models.DateTimeField(default=django.utils.timezone.now)),
                ('CreatedBy', models.CharField(default='SERVER', max_length=50)),
                ('Updated', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('UpdatedBy', models.CharField(default='SERVER', max_length=50, null=True)),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='thirdparties.client')),
            ],
            options={
                'db_table': 'ClientContact',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('ZipCode', models.CharField(max_length=255)),
                ('RFC', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('Phone1', models.CharField(max_length=25, null=True)),
                ('Phone2', models.CharField(max_length=25, null=True)),
                ('Created', models.DateTimeField(default=django.utils.timezone.now)),
                ('CreatedBy', models.CharField(default='SERVER', max_length=50)),
                ('Updated', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('UpdatedBy', models.CharField(default='SERVER', max_length=50, null=True)),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.city')),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.country')),
            ],
            options={
                'db_table': 'Supplier',
            },
        ),
    ]
