# Generated by Django 3.1.7 on 2021-03-07 23:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('thirdparties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='Created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='supplier',
            name='CreatedBy',
            field=models.CharField(default='SERVER', max_length=50),
        ),
        migrations.AddField(
            model_name='supplier',
            name='Updated',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='UpdatedBy',
            field=models.CharField(default='SERVER', max_length=50, null=True),
        ),
    ]
