# Generated by Django 3.1.7 on 2021-03-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thirdparties', '0002_auto_20210307_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Phone1',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='Phone2',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='Phone1',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='Phone2',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
