# Generated by Django 3.1.7 on 2021-03-09 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_city_country'),
        ('thirdparties', '0003_auto_20210307_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='City',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.city'),
        ),
        migrations.AlterField(
            model_name='client',
            name='Country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.country'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='City',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.city'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='Country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.country'),
        ),
    ]
