# Generated by Django 5.1.4 on 2025-01-09 23:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Created', models.DateTimeField(default=django.utils.timezone.now)),
                ('CreatedBy', models.CharField(default='SERVER', max_length=50)),
                ('Updated', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('UpdatedBy', models.CharField(default='SERVER', max_length=50, null=True)),
                ('Classification', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.classification')),
                ('Uom', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.uom')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
